# Generated by Django 3.2 on 2024-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardoffering',
            old_name='Points',
            new_name='TotalZhibi',
        ),
        migrations.RenameField(
            model_name='userrewardrecord',
            old_name='PointsAwarded',
            new_name='Zhibi',
        ),
        migrations.AddField(
            model_name='user',
            name='Zhibi',
            field=models.IntegerField(default=0),
        ),
    ]
