# Generated by Django 3.2 on 2024-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingquestion',
            name='MaxRating',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='ratingquestion',
            name='MinRating',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
