# Generated by Django 3.2 on 2024-06-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240602_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='Status',
            field=models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Submitted', 'Submitted'), ('Graded', 'Graded'), ('Deleted', 'Deleted')], max_length=20),
        ),
    ]
