# Generated by Django 3.2 on 2024-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240609_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Is_released',
            field=models.BooleanField(),
        ),
    ]
