# Generated by Django 3.2 on 2024-06-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='Is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
