# Generated by Django 3.2 on 2024-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_survey_is_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Is_released',
            field=models.BooleanField(blank=True),
        ),
    ]
