# Generated by Django 3.2 on 2024-06-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_survey_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Zhibi',
            new_name='zhibi',
        ),
        migrations.AddField(
            model_name='user',
            name='own_photos',
            field=models.TextField(default='[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'),
        ),
    ]
