# Generated by Django 3.2 on 2024-06-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_survey_is_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='Duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
