# Generated by Django 3.2 on 2024-06-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_submission_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='Duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
