# Generated by Django 3.2 on 2024-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_survey_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='own_photos',
            field=models.TextField(default='[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'),
        ),
    ]
