# Generated by Django 3.2 on 2024-06-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20240607_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='own_photos',
        ),
    ]
