# Generated by Django 3.2 on 2024-06-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_submission_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='Duration',
        ),
    ]
