# Generated by Django 3.2 on 2024-06-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_own_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='own_photos',
            field=models.TextField(default='[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'),
        ),
    ]
