# Generated by Django 3.2 on 2024-06-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_submission_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Is_open',
            field=models.BooleanField(default=True),
        ),
    ]
