# Generated by Django 3.2 on 2024-06-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_own_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratinganswer',
            name='RatingOptions',
        ),
        migrations.AddField(
            model_name='ratinganswer',
            name='Rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingquestion',
            name='MaxText',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ratingquestion',
            name='MinText',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ratingquestion',
            name='Score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='Score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='IsOrder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='QuotaLimit',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='surveystatistic',
            name='GradedResponses',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RatingOption',
        ),
    ]
