# Generated by Django 3.2 on 2024-06-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20240608_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blankanswer',
            name='GivenScore',
        ),
        migrations.RemoveField(
            model_name='surveystatistic',
            name='GradedResponses',
        ),
        migrations.AddField(
            model_name='blankquestion',
            name='CorrectAnswer',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
