# Generated by Django 3.2 on 2024-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_totalzhibi_rewardoffering_zhibi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blankquestion',
            old_name='Number',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='choicequestion',
            old_name='Number',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='ratingquestion',
            old_name='Number',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='blankquestion',
            name='QuestionNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='OptionNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='OptionCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='QuestionNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratingquestion',
            name='QuestionNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='PublishDate',
            field=models.DateTimeField(null=True),
        ),
    ]
