# Generated by Django 3.2 on 2024-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20240609_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='HasOtherOption',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='MaxSelectable',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
