# Generated by Django 3.2 on 2024-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20240609_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='HasOtherOption',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='MaxSelectable',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
