# Generated by Django 3.2 on 2024-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20240609_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankquestion',
            name='Score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='HasOtherOption',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='MaxSelectable',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='Score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratingquestion',
            name='Score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
