# Generated by Django 3.2 on 2024-05-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('SurveyID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, max_length=500)),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Draft', 'Draft')], max_length=20)),
                ('PublishDate', models.DateTimeField()),
                ('Category', models.CharField(max_length=20)),
                ('TotalScore', models.IntegerField(blank=True, null=True)),
                ('TimeLimit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_surveys',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('TemplateID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=50)),
                ('DefaultQuestionsJSON', models.JSONField()),
                ('Description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_users',
            },
        ),
        migrations.CreateModel(
            name='UserRewardRecord',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('PointsAwarded', models.IntegerField()),
                ('RedemptionDate', models.DateField()),
                ('Respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_records', to='app.user')),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='app.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyStatistic',
            fields=[
                ('StatisticID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalResponses', models.IntegerField(default=0)),
                ('AverageScore', models.FloatField(blank=True, null=True)),
                ('LastResponseDate', models.DateTimeField(blank=True, null=True)),
                ('Survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='app.survey')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='app.user'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('SubmissionID', models.AutoField(primary_key=True, serialize=False)),
                ('SubmissionTime', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Submitted', 'Submitted'), ('Graded', 'Graded')], max_length=20)),
                ('Duration', models.DurationField(blank=True, null=True)),
                ('Respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.user')),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.survey')),
            ],
        ),
        migrations.CreateModel(
            name='RewardOffering',
            fields=[
                ('RewardID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Points', models.IntegerField()),
                ('AvailableQuota', models.IntegerField()),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='app.survey')),
            ],
        ),
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('Number', models.IntegerField()),
                ('MinRating', models.IntegerField(default=1)),
                ('MaxRating', models.IntegerField(default=5)),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingquestion_questions', to='app.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ratingquestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratinganswer_answers', to='app.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('Number', models.IntegerField()),
                ('HasOtherOption', models.BooleanField(default=False)),
                ('MaxSelectable', models.IntegerField(default=1)),
                ('Score', models.IntegerField(blank=True, null=True)),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicequestion_questions', to='app.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.CharField(max_length=200)),
                ('IsCorrect', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.choicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.choiceoption')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.choicequestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choiceanswer_answers', to='app.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlankQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('Number', models.IntegerField()),
                ('Score', models.IntegerField(blank=True, null=True)),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blankquestion_questions', to='app.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlankAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(max_length=500)),
                ('GivenScore', models.IntegerField(blank=True, null=True)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blankquestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blankanswer_answers', to='app.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
