# Generated by Django 3.2 on 2024-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
