# Generated by Django 3.2 on 2024-05-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240528_0652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
